// Generated by disl-core from [INSTANTIATIONS.cpu.MAP] in system.tml.
// Do not edit by hand -- change the MAP in system.tml instead, so the
// hardware and this header cannot drift apart.

#ifndef DISL_GENERATED_ADDRESS_MAP_H
#define DISL_GENERATED_ADDRESS_MAP_H

#define  MEM      0x00000000
#define  GPIO     0x10000000
#define  UART     0x10000018
#define  TIMER    0x1000001C
#define  ETH_NIC  0x20000000
#define  CONFIG   0x80000000

#endif  // DISL_GENERATED_ADDRESS_MAP_H
